# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            Kennedy Odero
tagline:          'A blog about my wonderings in the net'
description:      'A blog about my wonderings in the net'
url:              http://kodero.github.io/

author:
  name:           'Kennedy Odero'
  url:            https://twitter.com/OderoK

paginate:         5

# Custom vars
version:          1.0.0

github:
  repo:           https://github.com/kodero/kodero.github.io

pages_list:       {'About':'/about','Archive':'/archive','Feed':'/atom.xml'}
